### ISSUE TITLE
What does the `synchronous` option do?

### ISSUE THREAD

**Issue by davej** [samiskin/redux-electron-store#12]
I'm struggling to understand what the `synchronous` option is for. It's set to `true` by default but I had to set it to `false` because otherwise it was duplicating all my actions.

**Comment by samiskin** [comment]
At my company we had all the actions forwarded to the main process, and then the update would be sent to all of the processes, including the origin of the action.  We then needed a way for a process to specify that it would run the actions on its own and not wait for updates because that process needed to perform the actions synchronously (it was interfacing with a webview which expected certain things).

If its duplicating actions then that sounds like a bug.  I believe the way it avoids duplicating actions is it checks the source parameter.

**Comment by davej** [comment]
Ah, I see the problem now, it's related to my PR. Will update in a little bit.

**Comment by davej** [comment]
So it was an issue related to my PR, I was comparing against the stringified version of the action (see commit ref above).
