### ISSUE TITLE
Compatibility with redux-saga

### ISSUE THREAD

**Issue by sam-jay** [samiskin/redux-electron-store#22]
Is this package compatible with sagas? If so, can someone give an example of how to configure it?

**Comment by samiskin** [comment]
No idea!  I haven't used sagas before.  Could you try just using redux saga, and this library together and telling me what happens?

Since you definitely know more about how they work than I do, I'll tell you what this library does and hopefully that gives you some intuition on whether sagas will work.

The way this library works is that it takes the old `store.dispatch` in the main process and replaces it with something like:
```
store old state
run the old store.dispatch
find out what changed
forward changes to renderer processes through an ipc message
```

the renderer processes then:
```
receive the ipc message which holds the changed data
runs an action that merges the changes into their respective stores
```

whenever an action is dispatched in a renderer process, the actions are forwarded to the main process where they are `store.dispatch`ed there too

This means that the order in which you put `electronEnhancer()` in your `compose` function does matter, as the `store old state, run old store.dispatch, find out what changed, forward changes` relies on the "old store.dispatch" being all the changes that should be synchronized.  Its therefore probably a good idea to keep the `electronEnhancer` call at the end of your `compose` function

**Comment by sam-jay** [comment]
It seems to be working a little too well and I'm confused why. I adapted the usage instructions in the readme as follows. 

```js
// renderer process
import createSagaMiddleware from 'redux-saga';
import { rootSaga } from '../sagas';

const sagaMiddleware = createSagaMiddleware();
const enhancer = compose(
  applyMiddleware(sagaMiddleware, ...otherMiddleware),
  electronEnhancer(),
  DevTools.instrument()
);
sagaMiddleware.run(rootSaga);

// rootSaga
import { delay } from 'redux-saga';
import { take, put, call } from 'redux-saga/effects';

export default function* rootSaga() {
  while (true) {
    yield take(REQUEST_TEST_ACTION);
    yield call(delay, 500);
    yield put({ type: TEST_ACTION });
  }
}
```

This saga will intercept each action of type REQUEST_TEST_ACTION, wait 500ms, and then dispatch an action called TEST_ACTION. 

Assume that TEST_ACTION increments a counter. We start with the counter at 0. Let's say I dispatch REQUEST_TEST_ACTION in the renderer process. If I understand correctly redux-electron-store will mirror this in the main process by also dispatching a REQUEST_TEST_ACTION. Now each saga in the two processes intercept this action, wait 500 ms, and dispatch a TEST_ACTION independently. Since TEST_ACTION gets dispatched in each process, I would assume that the one dispatched in main will trigger a TEST_ACTION in the renderer and vice versa. So TEST_ACTION will run twice in each process incrementing the counter to 2.

Surprisingly this doesn't actually happen and the counter is 1 at the end, which is ideal.

**Comment by samiskin** [comment]
I believe its because rather than the action itself being mirrored, its the changes in the store that are mirrored (to avoid repeating calculations if your reduction takes a while).  Once the action is ran to completion on the main process, the main processes forwards an action that looks like
```
{
    type: 'TEST_ACTION'
    updated: { count: 1 }
    deleted: {}
}
```

And then the renderer process merges its store data with the data from that action

**Comment by sam-jay** [comment]
Oh I see then the mirrored action doesn't travel along the middleware chain which means the saga will never process it. This should work perfectly for use cases where side-effects need only be handled in the process where the action originates. It will not work for performing background tasks in a secondary process in response to actions generated in another process.

**Comment by samiskin** [comment]
Yeah, the purpose of this library is solely data synchronization, so dealing with side effects are a bit out of scope.  If you do want to have more complicated functionality, you could also just copy all the files in `src` and place it in your own project to augment however you want.  I'd be happy to help out 😄 

I'll close this issue since it seems like things are generally resolved :+1:.
