### ISSUE TITLE
enhancement request: reselect support

### ISSUE THREAD

**Issue by bgrayburn** [samiskin/redux-electron-store#23]
it would be nice to keep selectors up to date and synced as store state. I'm not sure of the best way to keep them up to date at the moment to avoid running a bunch of comparisons in the memoized selectors all the time. Thanks for this awesome library!

**Comment by samiskin** [comment]
Could you elaborate on what exactly happens right now versus what you'd like to happen?

**Comment by bgrayburn** [comment]
Sure thing, at the moment this library syncs a redux store from main and renderer thread. If I add Selectors to the main process store, the results of those selectors should be made available on the renderer process. One way of doing this would be to update the state with the results of the selectors. As I'm thinking about this, it may be possible to use `remote` to retrieve information from the selectors without storing anything back to state. hmm.

that said, it would be nice if selector results could be similarly synced with the renderer process.

let me know if that makes sense and what you think about it. Thanks!

**Comment by samiskin** [comment]
Hmm, I'm not sure how that sort of thing would be accomplished within this library.  From my understanding, Selectors are just functions which store the value they last returned, so that if they're called again with the same inputs, they can just return that value rather than computing it again.  This is something completely separate from redux and the store.

To do this you might have to make changes to reselect's source.  Its only a single file so it shouldn't be too bad.  I don't think it would be worth it for most selectors though, since the overhead of the IPC calls is probably higher than the majority of your selectors' run time.

If you do end up doing something like that, then if it helps, I'll just explain how the synchronization is done in this library.  The way this library synchronizes the data is by first placing the main process' store in a global, and then when renderer's pop up and load their store, they will `remote` that global in to get their initial state.  Future state changes are all kept track of via `ipc` messages.

Since reselect is very much separate from redux, this is probably out of scope for `redux-electron-store`, so I'll close this issue.  Happy to help if you have more questions though!

**Comment by bgrayburn** [comment]
I understand it's out of scope, I'll look into implementing something
similar for reselect. Thank you for the information! I'll let you know if I
have any other questions
