### ISSUE TITLE
Not sure how to use it

### ISSUE THREAD

**Issue by demian85** [samiskin/redux-electron-store#40]
I have a few questions:

- What exactly is `dispatchProxy: a => store.dispatch(a)`? It's not documented in the API section.
- How many stores do I need? Can I create a single store in a module and use it both in the main & renderer process? Do I need 2 separate store modules, one with a filter and one without filter?
- Not sure if global scope is polluted with a store reference since it says `remote.getGlobal` is used. Not clear if I need to create a global reference to store or it's being done for me underneath...

Thanks.

**Comment by samiskin** [comment]
Hi, thanks for submitting this issue, I've updated the docs to address a couple of your points so that this hopefully doesn't happen to others.

- `dispatchProxy: a => store.dispatch(a)` is necessary because `electronEnhancer` needs to be able to `dispatch` actions for you whenever actions are dispatched in other processes.  If you omit this field, what happens is that if you had libraries that react to dispatches like `redux-logger`, they may not get notified of actions `electronEnhancer` dispatches.  The issue that prompted this addition was https://github.com/samiskin/redux-electron-store/issues/31
- You can use the same store in both the renderer and the main process.  The `filter` option is a no-op in the main process.  You can also use the same module but have `renderer` specific logic by checking `process.type === 'renderer'`.
- The global scope currently gets polluted by `__REDUX_ELECTRON_STORE__` which gets set to the `store` in the main process.  Its 100% an implementation detail and was necessary for `renderer`s to obtain their initial state, so I've now removed it from the `README` to avoid further confusions.

**Comment by demian85** [comment]
Ok great, but unfortunately, it seems that I'm having issues regarding references to objects created in the renderer process and accessing them from the main process.
Not sure how to solve this issue, for example, I have a VideoRecorder instance inside an async action module, but that action is also being required by the main process, so dispatching an action that uses that reference fails because it's undefined... Need to deal with magic here :/
Thanks for the clarification though.
