### ISSUE TITLE
Could not find electronEnhanced redux store in main process

### ISSUE THREAD

**Issue by Slapbox** [samiskin/redux-electron-store#59]
Awesome library! I'm having a bit of trouble unfortunately. I wonder if it's because I'm preloading my script into my `renderer` window.

As best as I can tell I've copied the example implementation completely, but no luck with getting past this message. Thanks for any help you can offer!

**Comment by Slapbox** [comment]
I think it was just a race issue.

**Comment by Aidenkwok** [comment]
@Slapbox how did you manage to fix this?

**Comment by Nantris** [comment]
I was trying to access the store in the main process before it was ready. If your issue is caused by the same, you have to ensure that your store is ready on the main process before you try to access it. I can't provide a more specific solution since it's going to vary based on your implementation - but you're going to need to rethink your implementation a bit.
